# Generated by Django 2.1.1 on 2019-02-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vminfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('VMNAME', models.CharField(max_length=200)),
                ('IPADDRESS', models.CharField(max_length=100, null=True)),
                ('USER', models.CharField(max_length=100, null=True)),
                ('OS', models.CharField(max_length=100, null=True)),
                ('INSTANCEUUID', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
